name: CI

on:
  push:
    branches:
      - "*"
      - "!master"
  pull_request:
    branches:
      - master

jobs:
  test:
    name: Test on node 24 and ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest]

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js 24
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: 'npm'

      - name: Setup C++ environment on linux
        uses: kurocha/setup-cpp@v1
        if: runner.os == 'Linux'

      - name: Install dependencies on linux
        run: sudo apt-get install -yq libblas-dev
        if: runner.os == 'Linux'

      - name: Install package dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Test
        run: npm test
