function usesFloat64VoidArrays(prototype) {
  return (
    prototype.wrapperName.startsWith('z') ||
    prototype.wrapperName.startsWith('dz') ||
    prototype.wrapperName === 'izamax'
  );
}

function pointerArrayType(prototype, param) {
  if (param.type.includes('float')) {
    return 'Napi::Float32Array';
  }

  if (param.type.includes('double')) {
    return 'Napi::Float64Array';
  }

  if (param.type.includes('void *')) {
    return usesFloat64VoidArrays(prototype) ? 'Napi::Float64Array' : 'Napi::Float32Array';
  }

  throw new Error(`Unsupported pointer parameter type "${param.type}" in ${prototype.cblasName}`);
}

function castType(param) {
  if (param.type.includes('*')) {
    if (param.type.includes('void')) {
      return param.type.includes('const') ? 'const void *' : 'void *';
    }

    if (param.type.includes('float')) {
      return param.type.includes('const') ? 'const float *' : 'float *';
    }

    if (param.type.includes('double')) {
      return param.type.includes('const') ? 'const double *' : 'double *';
    }
  }

  throw new Error(`Unsupported cast type "${param.type}"`);
}

function renderNumberExtractor(jsIndex, param) {
  if (param.type.includes('enum CBLAS_')) {
    const enumType = param.type.replace(/^const\s+/, '');
    return `static_cast<${enumType}>(${`info[${jsIndex}]`}.As<Napi::Number>().Int32Value())`;
  }

  if (param.type.includes('size_t') || param.type.includes('CBLAS_INDEX')) {
    return `static_cast<size_t>(info[${jsIndex}].As<Napi::Number>().Int64Value())`;
  }

  if (param.type.includes('float')) {
    return `static_cast<float>(info[${jsIndex}].As<Napi::Number>().FloatValue())`;
  }

  if (param.type.includes('double')) {
    return `info[${jsIndex}].As<Napi::Number>().DoubleValue()`;
  }

  if (param.type.includes('int')) {
    return `info[${jsIndex}].As<Napi::Number>().Int32Value()`;
  }

  throw new Error(`Unsupported numeric parameter type "${param.type}"`);
}

function renderParamDeclaration(prototype, param, jsIndex) {
  if (param.type.includes('*')) {
    const arrayType = pointerArrayType(prototype, param);
    const cast = castType(param);
    return `  auto ${param.name}Array = info[${jsIndex}].As<${arrayType}>();\n  ${cast} ${param.name} = reinterpret_cast<${cast}>(${param.name}Array.Data());`;
  }

  return `  const ${param.type.replace(/^const\s+/, '')} ${param.name} = ${renderNumberExtractor(jsIndex, param)};`;
}

function renderReturnStatement(prototype, callExpression) {
  if (prototype.returnType === 'void') {
    return `  ${callExpression};\n  return env.Undefined();`;
  }

  if (
    prototype.returnType === 'float' ||
    prototype.returnType === 'double' ||
    prototype.returnType === 'CBLAS_INDEX'
  ) {
    return `  return Napi::Number::New(env, ${callExpression});`;
  }

  throw new Error(`Unsupported return type "${prototype.returnType}" for ${prototype.cblasName}`);
}

export function renderRoutine(prototype) {
  const jsParams = prototype.params.filter((param) => !param.type.includes('enum CBLAS_ORDER'));
  const declarations = jsParams.map((param, jsIndex) => renderParamDeclaration(prototype, param, jsIndex));
  const callArgs = prototype.params.map((param) =>
    param.type.includes('enum CBLAS_ORDER') ? 'CblasRowMajor' : param.name
  );

  return `#include <napi.h>
#include "cblas.h"

Napi::Value ${prototype.wrapperName}(const Napi::CallbackInfo& info) {
  Napi::Env env = info.Env();
${declarations.join('\n')}
${renderReturnStatement(prototype, `${prototype.cblasName}(${callArgs.join(', ')})`)}
}
`;
}

export function renderIndexCc(routines) {
  const methods = routines.map(
    (routine) =>
      `  exports.Set(Napi::String::New(env, "${routine.wrapperName}"), Napi::Function::New(env, ${routine.wrapperName}));`
  );

  return `// This file is auto-generated by scripts/generate-native-glue.mjs.
// Do not edit it manually.

#include <napi.h>
#include "routines.h"

Napi::Object Init(Napi::Env env, Napi::Object exports) {
${methods.join('\n')}
  return exports;
}

NODE_API_MODULE(nblas, Init)
`;
}

export function renderRoutinesHeader(routines) {
  const declarations = routines.map(
    (routine) => `Napi::Value ${routine.wrapperName}(const Napi::CallbackInfo& info);`
  );

  return `// This file is auto-generated by scripts/generate-native-glue.mjs.
// Do not edit it manually.

#ifndef ROUTINES_H
#define ROUTINES_H

#include <napi.h>

${declarations.join('\n')}

#endif
`;
}

export function renderBindingGyp(sourceFiles) {
  const sources = ['src/index.cc', ...sourceFiles];
  const sourceLines = sources.map((source) => `        "${source}"`);

  return `{
  "targets": [
    {
      "target_name": "nblas",
      "sources": [
${sourceLines.join(',\n')}
      ],
      "include_dirs": [
        "<!@(node -p \\"require('node-addon-api').include\\")",
        "lib"
      ],
      "dependencies": [
        "<!(node -p \\"require('node-addon-api').gyp\\")"
      ],
      "defines": [
        "NAPI_DISABLE_CPP_EXCEPTIONS"
      ],
      "cflags!": [
        "-fno-exceptions"
      ],
      "cflags_cc!": [
        "-fno-exceptions"
      ],
      "conditions": [
        [
          "OS==\\"mac\\"",
          {
            "libraries": [
              "-framework Accelerate"
            ]
          },
          {
            "libraries": [
              "-lblas"
            ]
          }
        ]
      ]
    }
  ]
}
`;
}

export function renderTsParamType(prototype, param) {
  if (param.type.includes('*')) {
    if (param.type.includes('double')) {
      return 'Float64Array';
    }

    if (param.type.includes('float')) {
      return 'Float32Array';
    }

    if (param.type.includes('void *')) {
      return usesFloat64VoidArrays(prototype) ? 'Float64Array' : 'Float32Array';
    }
  }

  if (param.type.includes('enum CBLAS_TRANSPOSE')) {
    return '111 | 112 | 113';
  }

  if (param.type.includes('enum CBLAS_UPLO')) {
    return '121 | 122';
  }

  if (param.type.includes('enum CBLAS_DIAG')) {
    return '131 | 132';
  }

  if (param.type.includes('enum CBLAS_SIDE')) {
    return '141 | 142';
  }

  if (
    param.type.includes('int') ||
    param.type.includes('float') ||
    param.type.includes('double') ||
    param.type.includes('size_t') ||
    param.type.includes('CBLAS_INDEX')
  ) {
    return 'number';
  }

  throw new Error(`Unsupported TS parameter type "${param.type}" in ${prototype.cblasName}`);
}

export function renderTsReturnType(prototype) {
  if (prototype.returnType === 'void') {
    return 'void';
  }

  if (
    prototype.returnType === 'float' ||
    prototype.returnType === 'double' ||
    prototype.returnType === 'CBLAS_INDEX'
  ) {
    return 'number';
  }

  throw new Error(`Unsupported TS return type "${prototype.returnType}" in ${prototype.cblasName}`);
}

export function renderGeneratedNativeTypes(routines) {
  const lines = routines.map((routine) => {
    const params = routine.params
      .filter((param) => !param.type.includes('enum CBLAS_ORDER'))
      .map((param) => `${param.name}: ${renderTsParamType(routine, param)}`)
      .join(', ');

    return `  ${routine.wrapperName}(${params}): ${renderTsReturnType(routine)};`;
  });

  return `// This file is auto-generated by scripts/generate-native-glue.mjs.
// Do not edit it manually.

export interface INativeBlas {
${lines.join('\n')}
}
`;
}

export function renderGeneratedNativeTs(routines) {
  const exports = routines.map(
    (routine) => `export const ${routine.wrapperName}: INativeBlas['${routine.wrapperName}'] = nblas.${routine.wrapperName};`
  );

  return `// This file is auto-generated by scripts/generate-native-glue.mjs.
// Do not edit it manually.

import { INativeBlas } from './generated-native-types';

function loadNativeAddon(): INativeBlas {
  try {
    return require('../build/Release/nblas');
  } catch (releaseError) {
    try {
      return require('../build/Debug/nblas');
    } catch {
      const error = new Error('Failed to load the nblas native addon. Run \`npm run build\` first.');
      (error as Error & { cause?: unknown }).cause = releaseError;
      throw error;
    }
  }
}

const nblas = loadNativeAddon();

export default nblas;
${exports.join('\n')}
`;
}
